easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      list:
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          - {name: 'new', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
      form:
        fields:
          - {property: 'name'}
          - {property: 'slug'}